// Package publicapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package publicapi

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	AuthScopes = "auth.Scopes"
)

// Defines values for ClusterCloud.
const (
	Aws   ClusterCloud = "aws"
	Azure ClusterCloud = "azure"
	Gcp   ClusterCloud = "gcp"
)

// Defines values for ExecutionType.
const (
	Cleanup         ExecutionType = "cleanup"
	InplaceResize   ExecutionType = "inplace-resize"
	RegularEviction ExecutionType = "regular-eviction"
)

// Defines values for IndicatorName.
const (
	CpuRequestNotSet           IndicatorName = "CpuRequestNotSet"
	CpuThrottling              IndicatorName = "CpuThrottling"
	MemLimitNotSet             IndicatorName = "MemLimitNotSet"
	MemRequestNotSet           IndicatorName = "MemRequestNotSet"
	OOM                        IndicatorName = "OOM"
	OverProvisionedCpuRequest  IndicatorName = "OverProvisionedCpuRequest"
	OverProvisionedMemRequest  IndicatorName = "OverProvisionedMemRequest"
	RestartsObserved           IndicatorName = "RestartsObserved"
	UnderProvisionedCpuLimit   IndicatorName = "UnderProvisionedCpuLimit"
	UnderProvisionedCpuRequest IndicatorName = "UnderProvisionedCpuRequest"
	UnderProvisionedMemLimit   IndicatorName = "UnderProvisionedMemLimit"
	UnderProvisionedMemRequest IndicatorName = "UnderProvisionedMemRequest"
)

// Defines values for IndicatorSeverityLevel.
const (
	N0 IndicatorSeverityLevel = 0
	N1 IndicatorSeverityLevel = 1
	N2 IndicatorSeverityLevel = 2
	N3 IndicatorSeverityLevel = 3
)

// Defines values for IndicatorType.
const (
	None  IndicatorType = "none"
	Risk  IndicatorType = "risk"
	Waste IndicatorType = "waste"
)

// Defines values for InfraFitKarpenterRecommendationsType.
const (
	Karpenter InfraFitKarpenterRecommendationsType = "karpenter"
)

// Defines values for InfraFitStandardRecommendationsType.
const (
	Standard InfraFitStandardRecommendationsType = "standard"
)

// Defines values for OptimizationPolicy.
const (
	Balanced      OptimizationPolicy = "balanced"
	ExtraHeadroom OptimizationPolicy = "extraHeadroom"
	MaxHeadroom   OptimizationPolicy = "maxHeadroom"
	MaxSavings    OptimizationPolicy = "maxSavings"
)

// Defines values for OptimizationPolicyTimeWindow.
const (
	PolicyDefault OptimizationPolicyTimeWindow = "policyDefault"
	TimeWindow14d OptimizationPolicyTimeWindow = "14d"
	TimeWindow21d OptimizationPolicyTimeWindow = "21d"
	TimeWindow30d OptimizationPolicyTimeWindow = "30d"
	TimeWindow45d OptimizationPolicyTimeWindow = "45d"
)

// Defines values for WorkloadResilienceLevel.
const (
	High    WorkloadResilienceLevel = "high"
	Highest WorkloadResilienceLevel = "highest"
	Low     WorkloadResilienceLevel = "low"
	Medium  WorkloadResilienceLevel = "medium"
)

// AutomatedLogsContainer defines model for AutomatedLogsContainer.
type AutomatedLogsContainer struct {
	Cpu    AutomatedLogsContainerCpu    `json:"cpu"`
	Memory AutomatedLogsContainerMemory `json:"memory"`
	Name   string                       `json:"name"`
}

// AutomatedLogsContainerCpu defines model for AutomatedLogsContainerCpu.
type AutomatedLogsContainerCpu struct {
	CpuCoresLimits           int64   `json:"cpuCoresLimits"`
	CpuCoresRequest          int64   `json:"cpuCoresRequest"`
	CpuLimitChangeAbsolute   int64   `json:"cpuLimitChangeAbsolute"`
	CpuLimitChangePercent    float64 `json:"cpuLimitChangePercent"`
	CpuLimitImpact           int64   `json:"cpuLimitImpact"`
	CpuRequestChangeAbsolute int64   `json:"cpuRequestChangeAbsolute"`
	CpuRequestChangePercent  float64 `json:"cpuRequestChangePercent"`
	CpuRequestImpact         int64   `json:"cpuRequestImpact"`
	RecommendCpuCoresLimits  int64   `json:"recommendCpuCoresLimits"`
	RecommendCpuCoresRequest int64   `json:"recommendCpuCoresRequest"`
}

// AutomatedLogsContainerMemory defines model for AutomatedLogsContainerMemory.
type AutomatedLogsContainerMemory struct {
	MemLimitChangePercent       float64 `json:"memLimitChangePercent"`
	MemMiBLimitChangeAbsolute   int64   `json:"memMiBLimitChangeAbsolute"`
	MemMiBLimitImpact           int64   `json:"memMiBLimitImpact"`
	MemMiBLimits                int64   `json:"memMiBLimits"`
	MemMiBRequest               int64   `json:"memMiBRequest"`
	MemMiBRequestChangeAbsolute int64   `json:"memMiBRequestChangeAbsolute"`
	MemMiBRequestImpact         int64   `json:"memMiBRequestImpact"`
	MemRequestChangePercent     float64 `json:"memRequestChangePercent"`
	RecommendMemMiBLimits       int64   `json:"recommendMemMiBLimits"`
	RecommendMemMiBRequest      int64   `json:"recommendMemMiBRequest"`
}

// AutomationLogEntry defines model for AutomationLogEntry.
type AutomationLogEntry struct {
	ClusterName string                 `json:"cluster_name"`
	ClusterUid  string                 `json:"cluster_uid"`
	Container   AutomatedLogsContainer `json:"container"`
	Executed    ExecutionType          `json:"executed"`
	Labels      map[string]string      `json:"labels"`
	Namespace   string                 `json:"namespace"`

	// StartedAt Timestamp when the action started.
	StartedAt    time.Time `json:"started_at"`
	WorkloadId   string    `json:"workload_id"`
	WorkloadName string    `json:"workload_name"`
	WorkloadType string    `json:"workload_type"`
}

// CPUPercentiles Requested or used CPU percentiles for a node group/type, in cores.
type CPUPercentiles struct {
	AvgCores  float64 `json:"avgCores"`
	MaxCores  float64 `json:"maxCores"`
	MinCores  float64 `json:"minCores"`
	P80Cores  float64 `json:"p80Cores"`
	P95Cores  float64 `json:"p95Cores"`
	P999Cores float64 `json:"p999Cores"`
	P99Cores  float64 `json:"p99Cores"`
}

// CPUUtilization defines model for CPUUtilization.
type CPUUtilization struct {
	IdleCores *float64 `json:"idleCores"`

	// Requested Requested or used CPU percentiles for a node group/type, in cores.
	Requested CPUPercentiles `json:"requested"`

	// Used Requested or used CPU percentiles for a node group/type, in cores.
	Used CPUPercentiles `json:"used"`
}

// Cluster defines model for Cluster.
type Cluster struct {
	Cloud             *ClusterCloud `json:"cloud"`
	CreatedAt         time.Time     `json:"createdAt"`
	LastTransmittedAt time.Time     `json:"lastTransmittedAt"`
	Name              string        `json:"name"`
	Region            *string       `json:"region"`
	Uid               *string       `json:"uid"`
}

// ClusterCloud defines model for ClusterCloud.
type ClusterCloud string

// ClusterDetail defines model for ClusterDetail.
type ClusterDetail struct {
	Cloud             *ClusterCloud      `json:"cloud"`
	CreatedAt         time.Time          `json:"createdAt"`
	Emission          map[string]float64 `json:"emission"`
	LastTransmittedAt time.Time          `json:"lastTransmittedAt"`
	Name              string             `json:"name"`
	Region            *string            `json:"region"`
	Uid               *string            `json:"uid"`
}

// Container Detailed information about a specific container within the workload, including its performance indicators and usage statistics.
type Container struct {
	// Indicators A list of indicators providing insights into the performance and health of the container.
	Indicators []Indicator `json:"indicators"`

	// Name The name of the container.
	Name string `json:"name"`

	// Resources The resource allocation details for the workload, including the current and recommended by PerfectScale allocation.
	Resources struct {
		// Current Metrics detailing the resource allocation in terms of memory and CPU.
		Current Resources `json:"current"`

		// Recommended Metrics detailing the resource allocation in terms of memory and CPU.
		Recommended Resources `json:"recommended"`
	} `json:"resources"`

	// RunningMinutes The total number of minutes the container has been running.
	RunningMinutes int `json:"runningMinutes"`

	// Usage An object representing the resource usage statistics of a container, broken down into CPU and memory consumption.
	Usage struct {
		// CpuCores An object representing percentile statistics of resource usage, providing insights into the distribution of usage values over a certain period.
		CpuCores Percentiles `json:"cpuCores"`

		// MemoryMiB An object representing percentile statistics of resource usage, providing insights into the distribution of usage values over a certain period.
		MemoryMiB Percentiles `json:"memoryMiB"`
	} `json:"usage"`
}

// CostAnalysis Analysis of the costs associated with the workload's resource consumption over the past 30 days.
type CostAnalysis struct {
	// Next30Days Metrics detailing the total and wasted costs associated with the workload's resource consumption.
	Next30Days Next30DaysCostAnalysis `json:"next30Days"`

	// Past30Days Metrics detailing the total and wasted costs associated with the workload's resource consumption.
	Past30Days Past30DaysCostAnalysis `json:"past30Days"`
}

// CursorPagination Cursor pagination metadata. Direction is encoded inside the opaque token.
type CursorPagination struct {
	Next     *string `json:"next"`
	PageSize int     `json:"pageSize"`
	Prev     *string `json:"prev"`
}

// ExecutionType defines model for ExecutionType.
type ExecutionType string

// GPUIdle defines model for GPUIdle.
type GPUIdle struct {
	MemoryMiB float64 `json:"memoryMiB"`
	Units     float64 `json:"units"`
}

// GPUPercentiles Requested or used GPU percentiles for a node group/type, in device memory MiB and device-fraction units.
type GPUPercentiles struct {
	AvgMemoryMiB  float64 `json:"avgMemoryMiB"`
	AvgUnits      float64 `json:"avgUnits"`
	MaxMemoryMiB  float64 `json:"maxMemoryMiB"`
	MaxUnits      float64 `json:"maxUnits"`
	MinMemoryMiB  float64 `json:"minMemoryMiB"`
	MinUnits      float64 `json:"minUnits"`
	P80MemoryMiB  float64 `json:"p80MemoryMiB"`
	P80Units      float64 `json:"p80Units"`
	P95MemoryMiB  float64 `json:"p95MemoryMiB"`
	P95Units      float64 `json:"p95Units"`
	P999MemoryMiB float64 `json:"p999MemoryMiB"`
	P999Units     float64 `json:"p999Units"`
	P99MemoryMiB  float64 `json:"p99MemoryMiB"`
	P99Units      float64 `json:"p99Units"`
}

// GPUUtilization GPU utilization for a node group/type. Absent (null) when no GPU is present.
type GPUUtilization struct {
	Architectures *[]string `json:"architectures,omitempty"`
	Idle          *GPUIdle  `json:"idle,omitempty"`

	// Requested Requested or used GPU percentiles for a node group/type, in device memory MiB and device-fraction units.
	Requested   GPUPercentiles `json:"requested"`
	SharingType *[]string      `json:"sharingType,omitempty"`

	// Used Requested or used GPU percentiles for a node group/type, in device memory MiB and device-fraction units.
	Used GPUPercentiles `json:"used"`
}

// Indicator An object representing key performance indicators that provide insights into the performance and health of the workload or container.
type Indicator struct {
	// Name The name of the indicator representing a specific aspect of performance or health.
	Name IndicatorName `json:"name"`

	// SeverityLevel The severity level of the indicator, ranging from 0 (no issue) to 3 (critical issue).
	SeverityLevel IndicatorSeverityLevel `json:"severityLevel"`

	// Type The type of indicator, categorizing it as either a risk, waste, or no issue (none).
	Type IndicatorType `json:"type"`
}

// IndicatorName The name of the indicator representing a specific aspect of performance or health.
type IndicatorName string

// IndicatorSeverityLevel The severity level of the indicator, ranging from 0 (no issue) to 3 (critical issue).
type IndicatorSeverityLevel int

// IndicatorType The type of indicator, categorizing it as either a risk, waste, or no issue (none).
type IndicatorType string

// InfraFitKarpenterChange defines model for InfraFitKarpenterChange.
type InfraFitKarpenterChange struct {
	CurrentValue     string `json:"currentValue"`
	Id               string `json:"id"`
	Operation        string `json:"operation"`
	Path             string `json:"path"`
	Rationale        string `json:"rationale"`
	RecommendedValue string `json:"recommendedValue"`
	Title            string `json:"title"`
}

// InfraFitKarpenterRecommendations defines model for InfraFitKarpenterRecommendations.
type InfraFitKarpenterRecommendations struct {
	Changes []InfraFitKarpenterChange `json:"changes"`

	// CurrentConfig Full raw Karpenter NodePool custom resource, verbatim.
	CurrentConfig map[string]interface{} `json:"currentConfig"`
	HasChanges    bool                   `json:"hasChanges"`

	// RecommendedConfig Recommended Karpenter NodePool custom resource. May drop raw fields not modeled server-side when changes exist (lossy typed round-trip upstream).
	RecommendedConfig map[string]interface{}               `json:"recommendedConfig"`
	Type              InfraFitKarpenterRecommendationsType `json:"type"`
}

// InfraFitKarpenterRecommendationsType defines model for InfraFitKarpenterRecommendations.Type.
type InfraFitKarpenterRecommendationsType string

// InfraFitNodeGroup defines model for InfraFitNodeGroup.
type InfraFitNodeGroup struct {
	Architectures  *[]string       `json:"architectures,omitempty"`
	AutoscalerType string          `json:"autoscalerType"`
	Cost           NodeGroupCost   `json:"cost"`
	Cpu            CPUUtilization  `json:"cpu"`
	Gpu            *GPUUtilization `json:"gpu"`

	// Id Node group / node pool name.
	Id              string                           `json:"id"`
	Labels          *map[string]string               `json:"labels,omitempty"`
	Mem             MemUtilization                   `json:"mem"`
	NodeTypes       []InfraFitNodeType               `json:"nodeTypes"`
	Nodes           NodesCount                       `json:"nodes"`
	Pods            PodsCount                        `json:"pods"`
	Recommendations InfraFitNodeGroupRecommendations `json:"recommendations"`
	Reservations    *[]string                        `json:"reservations,omitempty"`
	RunningMinutes  *int                             `json:"runningMinutes,omitempty"`
	Seen            *SeenWindow                      `json:"seen,omitempty"`
}

// InfraFitNodeGroupRecommendations defines model for InfraFitNodeGroupRecommendations.
type InfraFitNodeGroupRecommendations struct {
	union json.RawMessage
}

// InfraFitNodeType defines model for InfraFitNodeType.
type InfraFitNodeType struct {
	Cost           NodeGroupCost   `json:"cost"`
	Cpu            CPUUtilization  `json:"cpu"`
	Gpu            *GPUUtilization `json:"gpu"`
	Id             string          `json:"id"`
	InstanceFamily *string         `json:"instanceFamily,omitempty"`
	InstanceType   string          `json:"instanceType"`
	IsSpot         *bool           `json:"isSpot,omitempty"`
	Mem            MemUtilization  `json:"mem"`
	Nodes          NodesCount      `json:"nodes"`
	Pods           PodsCount       `json:"pods"`
	RunningMinutes *int            `json:"runningMinutes,omitempty"`
	Seen           *SeenWindow     `json:"seen,omitempty"`
}

// InfraFitStandardNodeTypeRecommendation defines model for InfraFitStandardNodeTypeRecommendation.
type InfraFitStandardNodeTypeRecommendation struct {
	EstimatedSavings    float64 `json:"estimatedSavings"`
	EstimatedSavingsPct float64 `json:"estimatedSavingsPct"`
	HourlyCost          float64 `json:"hourlyCost"`
	Id                  string  `json:"id"`
	InstanceFamily      *string `json:"instanceFamily,omitempty"`
	InstanceType        string  `json:"instanceType"`
	NodeCount           int     `json:"nodeCount"`
}

// InfraFitStandardRecommendations defines model for InfraFitStandardRecommendations.
type InfraFitStandardRecommendations struct {
	HasChanges bool                                     `json:"hasChanges"`
	NodeTypes  []InfraFitStandardNodeTypeRecommendation `json:"nodeTypes"`
	Type       InfraFitStandardRecommendationsType      `json:"type"`
}

// InfraFitStandardRecommendationsType defines model for InfraFitStandardRecommendations.Type.
type InfraFitStandardRecommendationsType string

// MemPercentiles Requested or used memory percentiles for a node group/type, in MiB.
type MemPercentiles struct {
	AvgMiB  float64 `json:"avgMiB"`
	MaxMiB  float64 `json:"maxMiB"`
	MinMiB  float64 `json:"minMiB"`
	P80MiB  float64 `json:"p80MiB"`
	P95MiB  float64 `json:"p95MiB"`
	P999MiB float64 `json:"p999MiB"`
	P99MiB  float64 `json:"p99MiB"`
}

// MemUtilization defines model for MemUtilization.
type MemUtilization struct {
	IdleMiB *float64 `json:"idleMiB"`

	// Requested Requested or used memory percentiles for a node group/type, in MiB.
	Requested MemPercentiles `json:"requested"`

	// Used Requested or used memory percentiles for a node group/type, in MiB.
	Used MemPercentiles `json:"used"`
}

// Money A monetary value. amount is a decimal string for transport fidelity — parse client-side for arithmetic.
type Money struct {
	Amount   string `json:"amount"`
	Currency string `json:"currency"`
}

// MuteStatus defines model for MuteStatus.
type MuteStatus struct {
	// Expires The date and time when the workload will automatically become unmuted. If null, the mute status does not expire automatically.
	Expires *time.Time `json:"expires"`

	// IsMuted Indicates whether the workload is currently muted.
	IsMuted bool `json:"isMuted"`
}

// Next30DaysCostAnalysis Metrics detailing the total and wasted costs associated with the workload's resource consumption.
type Next30DaysCostAnalysis struct {
	// CostIncrease The workload total cost increase.
	CostIncrease float64 `json:"costIncrease"`

	// PotentialSavings The potential savings for the workload.
	PotentialSavings float64 `json:"potentialSavings"`
}

// NodeGroupCost defines model for NodeGroupCost.
type NodeGroupCost struct {
	// Hourly A monetary value. amount is a decimal string for transport fidelity — parse client-side for arithmetic.
	Hourly Money             `json:"hourly"`
	Idle   NodeGroupIdleCost `json:"idle"`

	// Timeframe A monetary value. amount is a decimal string for transport fidelity — parse client-side for arithmetic.
	Timeframe Money `json:"timeframe"`
}

// NodeGroupIdleCost defines model for NodeGroupIdleCost.
type NodeGroupIdleCost struct {
	// Cpu A monetary value. amount is a decimal string for transport fidelity — parse client-side for arithmetic.
	Cpu Money  `json:"cpu"`
	Gpu *Money `json:"gpu"`

	// Mem A monetary value. amount is a decimal string for transport fidelity — parse client-side for arithmetic.
	Mem Money `json:"mem"`

	// Total A monetary value. amount is a decimal string for transport fidelity — parse client-side for arithmetic.
	Total Money `json:"total"`
}

// NodesCount defines model for NodesCount.
type NodesCount struct {
	Avg float64 `json:"avg"`
	Max float64 `json:"max"`
	Min float64 `json:"min"`
}

// OptimizationPolicy The optimization policy determining resource allocation strategy.
type OptimizationPolicy string

// OptimizationPolicyTimeWindow The time window for optimization policy.
type OptimizationPolicyTimeWindow string

// Pagination defines model for Pagination.
type Pagination struct {
	HasNext  bool    `json:"has_next"`
	HasPrev  bool    `json:"has_prev"`
	Next     *string `json:"next"`
	PageSize int     `json:"page_size"`
	Prev     *string `json:"prev"`
}

// Past30DaysCostAnalysis Metrics detailing the total and wasted costs associated with the workload's resource consumption.
type Past30DaysCostAnalysis struct {
	// CostPerHour The cost of the workload per hour.
	CostPerHour float64 `json:"costPerHour"`

	// TotalCost The total cost incurred by the workload's resource consumption.
	TotalCost float64 `json:"totalCost"`

	// WastedCost The cost attributed to over-provisioned or inefficiently utilized resources.
	WastedCost float64 `json:"wastedCost"`
}

// Percentiles An object representing percentile statistics of resource usage, providing insights into the distribution of usage values over a certain period.
type Percentiles struct {
	// P100 The 100th percentile value (or maximum value) of resource usage observed during the specified period.
	P100 float64 `json:"p100"`

	// P90 The 90th percentile value of resource usage, indicating that 90% of the usage values are below this value and 10% are above.
	P90 float64 `json:"p90"`

	// P95 The 95th percentile value of resource usage, indicating that 95% of the usage values are below this value and 5% are above.
	P95 float64 `json:"p95"`
}

// PodsCount defines model for PodsCount.
type PodsCount struct {
	Allocatable int     `json:"allocatable"`
	AvgCount    float64 `json:"avgCount"`
	Capacity    int     `json:"capacity"`
}

// ReplicasCounts An object representing the count statistics of replicas for a workload over a month period.
type ReplicasCounts struct {
	// AvgCount The average count of replicas observed for the workload during the month period.
	AvgCount int `json:"avgCount"`

	// MaxCount The maximum count of replicas observed for the workload during the month period.
	MaxCount int `json:"maxCount"`
}

// Resources Metrics detailing the resource allocation in terms of memory and CPU.
type Resources struct {
	// CpuLimitCores The maximum amount of CPU resources that can be allocated for the workload in cores.
	CpuLimitCores float64 `json:"cpuLimitCores"`

	// CpuRequestCores The amount of CPU resources requested for the workload in cores.
	CpuRequestCores float64 `json:"cpuRequestCores"`

	// MemoryLimitMiB The maximum amount of memory that can be allocated for the workload in MiB.
	MemoryLimitMiB float64 `json:"memoryLimitMiB"`

	// MemoryRequestMiB The amount of memory requested for the workload in MiB.
	MemoryRequestMiB float64 `json:"memoryRequestMiB"`
}

// SeenWindow defines model for SeenWindow.
type SeenWindow struct {
	FirstTime time.Time `json:"firstTime"`
	LastTime  time.Time `json:"lastTime"`
}

// Workload defines model for Workload.
type Workload struct {
	// Containers An object holding detailed information about each container within the workload.
	Containers []Container `json:"containers"`

	// CostAnalysis Analysis of the costs associated with the workload's resource consumption over the past 30 days.
	CostAnalysis CostAnalysis `json:"costAnalysis"`

	// CpuOptimizationPolicy The CPU-specific optimization policy.
	CpuOptimizationPolicy OptimizationPolicy `json:"cpuOptimizationPolicy"`

	// FirstSeen The timestamp when the workload was first observed.
	FirstSeen time.Time `json:"firstSeen"`

	// Id A unique identifier for the workload, usually following a namespace-type-name convention.
	Id string `json:"id"`

	// Indicators A list of indicators providing insights into the performance and health of the workload.
	Indicators []Indicator `json:"indicators"`

	// LastSeen The timestamp when the workload was last observed.
	LastSeen time.Time `json:"lastSeen"`

	// MemoryOptimizationPolicy The memory-specific optimization policy.
	MemoryOptimizationPolicy OptimizationPolicy `json:"memoryOptimizationPolicy"`

	// MemoryRequestEqualsLimit Whether memory request equals limit is enabled.
	MemoryRequestEqualsLimit bool       `json:"memoryRequestEqualsLimit"`
	MuteStatus               MuteStatus `json:"muteStatus"`

	// Name A human-readable name for the workload.
	Name string `json:"name"`

	// Namespace The Kubernetes namespace in which the workload resides.
	Namespace string `json:"namespace"`

	// OptimizationPolicy The optimization policy applied to the workload.
	OptimizationPolicy OptimizationPolicy `json:"optimizationPolicy"`

	// OptimizationPolicyTimeWindow The time window for optimization policy.
	OptimizationPolicyTimeWindow OptimizationPolicyTimeWindow `json:"optimizationPolicyTimeWindow"`

	// ReplicasCounts An object representing the count statistics of replicas for a workload over a month period.
	ReplicasCounts ReplicasCounts `json:"replicasCounts"`

	// ResilienceLevel **Deprecated**: Use `optimizationPolicy` instead. The resilience level of the workload (configured on Perfectscale side).
	//
	// Mapping to optimizationPolicy values:
	// - `low` → `maxSavings`
	// - `medium` → `balanced`
	// - `high` → `extraHeadroom`
	// - `highest` → `maxHeadroom`
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	ResilienceLevel WorkloadResilienceLevel `json:"resilienceLevel"`

	// RunningMinutes The total number of minutes the workload has been running.
	RunningMinutes int `json:"runningMinutes"`

	// Type The type of Kubernetes workload. Common types include Deployment, StatefulSet, and DaemonSet, but other string values can also be used to represent custom or extended workload types.
	Type string `json:"type"`

	// WorkloadLabels Key-value pairs representing kubernets labels associated with the workload.
	WorkloadLabels map[string]string `json:"workloadLabels"`
}

// WorkloadResilienceLevel **Deprecated**: Use `optimizationPolicy` instead. The resilience level of the workload (configured on Perfectscale side).
//
// Mapping to optimizationPolicy values:
// - `low` → `maxSavings`
// - `medium` → `balanced`
// - `high` → `extraHeadroom`
// - `highest` → `maxHeadroom`
type WorkloadResilienceLevel string

// AutomationAuditLogsJSONBody defines parameters for AutomationAuditLogs.
type AutomationAuditLogsJSONBody struct {
	// After Cursor token from a previous response's pagination.next, used to fetch the next page.
	After *string `json:"after,omitempty"`

	// Before Cursor token from a previous response's pagination.prev, used to fetch the previous page.
	Before *string `json:"before,omitempty"`

	// ClusterUids Filter by cluster UIDs.
	ClusterUids *[]string `json:"cluster_uids,omitempty"`

	// From The start of the time range in ISO 8601 format with UTC timezone.
	// Defaults server-side to 30 days ago if omitted. Cannot be earlier than 30 days ago.
	From *time.Time `json:"from,omitempty"`

	// Namespaces Filter by Kubernetes namespaces.
	Namespaces *[]string `json:"namespaces,omitempty"`

	// PageSize The maximum number of items to return. Defaults to 1000. Must be between 1 and 5000.
	PageSize *int `json:"page_size,omitempty"`

	// To The end of the time range in ISO 8601 format with UTC timezone.
	// Defaults server-side to "now" if omitted.
	To *time.Time `json:"to,omitempty"`
}

// GetClusterParams defines parameters for GetCluster.
type GetClusterParams struct {
	// Period The period for which carbon emission is calculated
	Period *string `form:"period,omitempty" json:"period,omitempty"`
}

// ListInfraFitNodeGroupsParams defines parameters for ListInfraFitNodeGroups.
type ListInfraFitNodeGroupsParams struct {
	// Period ISO-8601 duration window for utilization/cost figures (e.g. P30D). Recommendations always use a 30 day window.
	Period   *string `form:"period,omitempty" json:"period,omitempty"`
	PageSize *int    `form:"pageSize,omitempty" json:"pageSize,omitempty"`

	// PageToken Opaque, direction-encoded cursor from a previous response's meta.pagination.next or prev.
	PageToken *string `form:"pageToken,omitempty" json:"pageToken,omitempty"`

	// RecommendationLimit Caps node-type recommendations per node group. Karpenter pools always return the full change set.
	RecommendationLimit *int `form:"recommendationLimit,omitempty" json:"recommendationLimit,omitempty"`

	// HasRecommendations When true, only node groups with at least one actionable recommendation. When false, only node groups without recommendations.
	HasRecommendations *bool `form:"hasRecommendations,omitempty" json:"hasRecommendations,omitempty"`

	// IncludeMuted When true, includes muted recommendations.
	IncludeMuted *bool `form:"includeMuted,omitempty" json:"includeMuted,omitempty"`

	// AutoscalerType Filter by autoscaler type (e.g. karpenter, cluster_autoscaler).
	AutoscalerType *string `form:"autoscalerType,omitempty" json:"autoscalerType,omitempty"`
}

// GetInfraFitNodeGroupParams defines parameters for GetInfraFitNodeGroup.
type GetInfraFitNodeGroupParams struct {
	Period              *string `form:"period,omitempty" json:"period,omitempty"`
	RecommendationLimit *int    `form:"recommendationLimit,omitempty" json:"recommendationLimit,omitempty"`
}

// AutomationAuditLogsJSONRequestBody defines body for AutomationAuditLogs for application/json ContentType.
type AutomationAuditLogsJSONRequestBody AutomationAuditLogsJSONBody

// AsInfraFitStandardRecommendations returns the union data inside the InfraFitNodeGroupRecommendations as a InfraFitStandardRecommendations
func (t InfraFitNodeGroupRecommendations) AsInfraFitStandardRecommendations() (InfraFitStandardRecommendations, error) {
	var body InfraFitStandardRecommendations
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInfraFitStandardRecommendations overwrites any union data inside the InfraFitNodeGroupRecommendations as the provided InfraFitStandardRecommendations
func (t *InfraFitNodeGroupRecommendations) FromInfraFitStandardRecommendations(v InfraFitStandardRecommendations) error {
	v.Type = "standard"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInfraFitStandardRecommendations performs a merge with any union data inside the InfraFitNodeGroupRecommendations, using the provided InfraFitStandardRecommendations
func (t *InfraFitNodeGroupRecommendations) MergeInfraFitStandardRecommendations(v InfraFitStandardRecommendations) error {
	v.Type = "standard"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsInfraFitKarpenterRecommendations returns the union data inside the InfraFitNodeGroupRecommendations as a InfraFitKarpenterRecommendations
func (t InfraFitNodeGroupRecommendations) AsInfraFitKarpenterRecommendations() (InfraFitKarpenterRecommendations, error) {
	var body InfraFitKarpenterRecommendations
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInfraFitKarpenterRecommendations overwrites any union data inside the InfraFitNodeGroupRecommendations as the provided InfraFitKarpenterRecommendations
func (t *InfraFitNodeGroupRecommendations) FromInfraFitKarpenterRecommendations(v InfraFitKarpenterRecommendations) error {
	v.Type = "karpenter"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInfraFitKarpenterRecommendations performs a merge with any union data inside the InfraFitNodeGroupRecommendations, using the provided InfraFitKarpenterRecommendations
func (t *InfraFitNodeGroupRecommendations) MergeInfraFitKarpenterRecommendations(v InfraFitKarpenterRecommendations) error {
	v.Type = "karpenter"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t InfraFitNodeGroupRecommendations) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t InfraFitNodeGroupRecommendations) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "karpenter":
		return t.AsInfraFitKarpenterRecommendations()
	case "standard":
		return t.AsInfraFitStandardRecommendations()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t InfraFitNodeGroupRecommendations) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *InfraFitNodeGroupRecommendations) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// AutomationAuditLogsWithBody request with any body
	AutomationAuditLogsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AutomationAuditLogs(ctx context.Context, body AutomationAuditLogsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetClusters request
	GetClusters(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteCluster request
	DeleteCluster(ctx context.Context, clusterUid string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCluster request
	GetCluster(ctx context.Context, clusterUid string, params *GetClusterParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListInfraFitNodeGroups request
	ListInfraFitNodeGroups(ctx context.Context, clusterUid string, params *ListInfraFitNodeGroupsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetInfraFitNodeGroup request
	GetInfraFitNodeGroup(ctx context.Context, clusterUid string, nodeGroupName string, params *GetInfraFitNodeGroupParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetClustersClusterUidWorkloads request
	GetClustersClusterUidWorkloads(ctx context.Context, clusterUid string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) AutomationAuditLogsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAutomationAuditLogsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AutomationAuditLogs(ctx context.Context, body AutomationAuditLogsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAutomationAuditLogsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetClusters(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetClustersRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteCluster(ctx context.Context, clusterUid string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteClusterRequest(c.Server, clusterUid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCluster(ctx context.Context, clusterUid string, params *GetClusterParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetClusterRequest(c.Server, clusterUid, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListInfraFitNodeGroups(ctx context.Context, clusterUid string, params *ListInfraFitNodeGroupsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListInfraFitNodeGroupsRequest(c.Server, clusterUid, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetInfraFitNodeGroup(ctx context.Context, clusterUid string, nodeGroupName string, params *GetInfraFitNodeGroupParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetInfraFitNodeGroupRequest(c.Server, clusterUid, nodeGroupName, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetClustersClusterUidWorkloads(ctx context.Context, clusterUid string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetClustersClusterUidWorkloadsRequest(c.Server, clusterUid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewAutomationAuditLogsRequest calls the generic AutomationAuditLogs builder with application/json body
func NewAutomationAuditLogsRequest(server string, body AutomationAuditLogsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAutomationAuditLogsRequestWithBody(server, "application/json", bodyReader)
}

// NewAutomationAuditLogsRequestWithBody generates requests for AutomationAuditLogs with any type of body
func NewAutomationAuditLogsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/automation/audit_logs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetClustersRequest generates requests for GetClusters
func NewGetClustersRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/clusters")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteClusterRequest generates requests for DeleteCluster
func NewDeleteClusterRequest(server string, clusterUid string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "cluster_uid", runtime.ParamLocationPath, clusterUid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/clusters/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetClusterRequest generates requests for GetCluster
func NewGetClusterRequest(server string, clusterUid string, params *GetClusterParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "cluster_uid", runtime.ParamLocationPath, clusterUid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/clusters/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Period != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "period", runtime.ParamLocationQuery, *params.Period); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListInfraFitNodeGroupsRequest generates requests for ListInfraFitNodeGroups
func NewListInfraFitNodeGroupsRequest(server string, clusterUid string, params *ListInfraFitNodeGroupsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "cluster_uid", runtime.ParamLocationPath, clusterUid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/clusters/%s/node-groups", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Period != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "period", runtime.ParamLocationQuery, *params.Period); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "pageSize", runtime.ParamLocationQuery, *params.PageSize); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PageToken != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "pageToken", runtime.ParamLocationQuery, *params.PageToken); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.RecommendationLimit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "recommendationLimit", runtime.ParamLocationQuery, *params.RecommendationLimit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.HasRecommendations != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "hasRecommendations", runtime.ParamLocationQuery, *params.HasRecommendations); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.IncludeMuted != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "includeMuted", runtime.ParamLocationQuery, *params.IncludeMuted); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.AutoscalerType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "autoscalerType", runtime.ParamLocationQuery, *params.AutoscalerType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetInfraFitNodeGroupRequest generates requests for GetInfraFitNodeGroup
func NewGetInfraFitNodeGroupRequest(server string, clusterUid string, nodeGroupName string, params *GetInfraFitNodeGroupParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "cluster_uid", runtime.ParamLocationPath, clusterUid)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "node_group_name", runtime.ParamLocationPath, nodeGroupName)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/clusters/%s/node-groups/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Period != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "period", runtime.ParamLocationQuery, *params.Period); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.RecommendationLimit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "recommendationLimit", runtime.ParamLocationQuery, *params.RecommendationLimit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetClustersClusterUidWorkloadsRequest generates requests for GetClustersClusterUidWorkloads
func NewGetClustersClusterUidWorkloadsRequest(server string, clusterUid string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "cluster_uid", runtime.ParamLocationPath, clusterUid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/clusters/%s/workloads", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// AutomationAuditLogsWithBodyWithResponse request with any body
	AutomationAuditLogsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AutomationAuditLogsResponse, error)

	AutomationAuditLogsWithResponse(ctx context.Context, body AutomationAuditLogsJSONRequestBody, reqEditors ...RequestEditorFn) (*AutomationAuditLogsResponse, error)

	// GetClustersWithResponse request
	GetClustersWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetClustersResponse, error)

	// DeleteClusterWithResponse request
	DeleteClusterWithResponse(ctx context.Context, clusterUid string, reqEditors ...RequestEditorFn) (*DeleteClusterResponse, error)

	// GetClusterWithResponse request
	GetClusterWithResponse(ctx context.Context, clusterUid string, params *GetClusterParams, reqEditors ...RequestEditorFn) (*GetClusterResponse, error)

	// ListInfraFitNodeGroupsWithResponse request
	ListInfraFitNodeGroupsWithResponse(ctx context.Context, clusterUid string, params *ListInfraFitNodeGroupsParams, reqEditors ...RequestEditorFn) (*ListInfraFitNodeGroupsResponse, error)

	// GetInfraFitNodeGroupWithResponse request
	GetInfraFitNodeGroupWithResponse(ctx context.Context, clusterUid string, nodeGroupName string, params *GetInfraFitNodeGroupParams, reqEditors ...RequestEditorFn) (*GetInfraFitNodeGroupResponse, error)

	// GetClustersClusterUidWorkloadsWithResponse request
	GetClustersClusterUidWorkloadsWithResponse(ctx context.Context, clusterUid string, reqEditors ...RequestEditorFn) (*GetClustersClusterUidWorkloadsResponse, error)
}

type AutomationAuditLogsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data []AutomationLogEntry `json:"data"`
		Meta struct {
			Pagination Pagination `json:"pagination"`
		} `json:"meta"`
	}
}

// Status returns HTTPResponse.Status
func (r AutomationAuditLogsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AutomationAuditLogsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetClustersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data []Cluster `json:"data"`
	}
}

// Status returns HTTPResponse.Status
func (r GetClustersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetClustersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteClusterResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteClusterResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteClusterResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetClusterResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data ClusterDetail `json:"data"`
	}
}

// Status returns HTTPResponse.Status
func (r GetClusterResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetClusterResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListInfraFitNodeGroupsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data []InfraFitNodeGroup `json:"data"`
		Meta struct {
			// Pagination Cursor pagination metadata. Direction is encoded inside the opaque token.
			Pagination CursorPagination `json:"pagination"`
			Timeframe  string           `json:"timeframe"`
		} `json:"meta"`
	}
}

// Status returns HTTPResponse.Status
func (r ListInfraFitNodeGroupsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListInfraFitNodeGroupsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetInfraFitNodeGroupResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data InfraFitNodeGroup `json:"data"`
	}
}

// Status returns HTTPResponse.Status
func (r GetInfraFitNodeGroupResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetInfraFitNodeGroupResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetClustersClusterUidWorkloadsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data []Workload `json:"data"`
		Meta struct {
			// Count The total number of workloads in the specified cluster.
			Count int `json:"count"`
		} `json:"meta"`
	}
}

// Status returns HTTPResponse.Status
func (r GetClustersClusterUidWorkloadsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetClustersClusterUidWorkloadsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// AutomationAuditLogsWithBodyWithResponse request with arbitrary body returning *AutomationAuditLogsResponse
func (c *ClientWithResponses) AutomationAuditLogsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AutomationAuditLogsResponse, error) {
	rsp, err := c.AutomationAuditLogsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAutomationAuditLogsResponse(rsp)
}

func (c *ClientWithResponses) AutomationAuditLogsWithResponse(ctx context.Context, body AutomationAuditLogsJSONRequestBody, reqEditors ...RequestEditorFn) (*AutomationAuditLogsResponse, error) {
	rsp, err := c.AutomationAuditLogs(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAutomationAuditLogsResponse(rsp)
}

// GetClustersWithResponse request returning *GetClustersResponse
func (c *ClientWithResponses) GetClustersWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetClustersResponse, error) {
	rsp, err := c.GetClusters(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetClustersResponse(rsp)
}

// DeleteClusterWithResponse request returning *DeleteClusterResponse
func (c *ClientWithResponses) DeleteClusterWithResponse(ctx context.Context, clusterUid string, reqEditors ...RequestEditorFn) (*DeleteClusterResponse, error) {
	rsp, err := c.DeleteCluster(ctx, clusterUid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteClusterResponse(rsp)
}

// GetClusterWithResponse request returning *GetClusterResponse
func (c *ClientWithResponses) GetClusterWithResponse(ctx context.Context, clusterUid string, params *GetClusterParams, reqEditors ...RequestEditorFn) (*GetClusterResponse, error) {
	rsp, err := c.GetCluster(ctx, clusterUid, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetClusterResponse(rsp)
}

// ListInfraFitNodeGroupsWithResponse request returning *ListInfraFitNodeGroupsResponse
func (c *ClientWithResponses) ListInfraFitNodeGroupsWithResponse(ctx context.Context, clusterUid string, params *ListInfraFitNodeGroupsParams, reqEditors ...RequestEditorFn) (*ListInfraFitNodeGroupsResponse, error) {
	rsp, err := c.ListInfraFitNodeGroups(ctx, clusterUid, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListInfraFitNodeGroupsResponse(rsp)
}

// GetInfraFitNodeGroupWithResponse request returning *GetInfraFitNodeGroupResponse
func (c *ClientWithResponses) GetInfraFitNodeGroupWithResponse(ctx context.Context, clusterUid string, nodeGroupName string, params *GetInfraFitNodeGroupParams, reqEditors ...RequestEditorFn) (*GetInfraFitNodeGroupResponse, error) {
	rsp, err := c.GetInfraFitNodeGroup(ctx, clusterUid, nodeGroupName, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetInfraFitNodeGroupResponse(rsp)
}

// GetClustersClusterUidWorkloadsWithResponse request returning *GetClustersClusterUidWorkloadsResponse
func (c *ClientWithResponses) GetClustersClusterUidWorkloadsWithResponse(ctx context.Context, clusterUid string, reqEditors ...RequestEditorFn) (*GetClustersClusterUidWorkloadsResponse, error) {
	rsp, err := c.GetClustersClusterUidWorkloads(ctx, clusterUid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetClustersClusterUidWorkloadsResponse(rsp)
}

// ParseAutomationAuditLogsResponse parses an HTTP response from a AutomationAuditLogsWithResponse call
func ParseAutomationAuditLogsResponse(rsp *http.Response) (*AutomationAuditLogsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AutomationAuditLogsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data []AutomationLogEntry `json:"data"`
			Meta struct {
				Pagination Pagination `json:"pagination"`
			} `json:"meta"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetClustersResponse parses an HTTP response from a GetClustersWithResponse call
func ParseGetClustersResponse(rsp *http.Response) (*GetClustersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetClustersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data []Cluster `json:"data"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDeleteClusterResponse parses an HTTP response from a DeleteClusterWithResponse call
func ParseDeleteClusterResponse(rsp *http.Response) (*DeleteClusterResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteClusterResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetClusterResponse parses an HTTP response from a GetClusterWithResponse call
func ParseGetClusterResponse(rsp *http.Response) (*GetClusterResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetClusterResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data ClusterDetail `json:"data"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListInfraFitNodeGroupsResponse parses an HTTP response from a ListInfraFitNodeGroupsWithResponse call
func ParseListInfraFitNodeGroupsResponse(rsp *http.Response) (*ListInfraFitNodeGroupsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListInfraFitNodeGroupsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data []InfraFitNodeGroup `json:"data"`
			Meta struct {
				// Pagination Cursor pagination metadata. Direction is encoded inside the opaque token.
				Pagination CursorPagination `json:"pagination"`
				Timeframe  string           `json:"timeframe"`
			} `json:"meta"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetInfraFitNodeGroupResponse parses an HTTP response from a GetInfraFitNodeGroupWithResponse call
func ParseGetInfraFitNodeGroupResponse(rsp *http.Response) (*GetInfraFitNodeGroupResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetInfraFitNodeGroupResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data InfraFitNodeGroup `json:"data"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetClustersClusterUidWorkloadsResponse parses an HTTP response from a GetClustersClusterUidWorkloadsWithResponse call
func ParseGetClustersClusterUidWorkloadsResponse(rsp *http.Response) (*GetClustersClusterUidWorkloadsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetClustersClusterUidWorkloadsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data []Workload `json:"data"`
			Meta struct {
				// Count The total number of workloads in the specified cluster.
				Count int `json:"count"`
			} `json:"meta"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
